pywren: 
    storage_bucket: <BUCKET_NAME>
    storage_backend: gcp_functions
    compute_backend: gcp_storage
    compute_backend_region : <REGION_NAME>

gcp:
    project_name : <PROJECT_NAME>
    service_account : <SERVICE_ACCOUNT_EMAIL>
    credentials_path : <FULL_PATH_TO_CREDENTIALS_JSON>
    region : <REGION_NAME>
